Lesson5
miheykrug/qna pull request #3
Opened 2018-04-26 23:29 UTC by miheykrug

2018-04-27 08:58 UTC, vkurennov requested changes

2018-04-27 08:58 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user == @answer.user
* 1. Лучше сравнивать по user_id, чтобы не грузить ассоциацию из базы, она ведь не нужна.
* 2. Т.к. такая проверка будет встречаться часто, то лучше ее вынести в метод `User#author_of?`

2018-04-27 08:58 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body).merge({ user_id: current_user.id })
Не стоит так делать. strong params задают белый список параметров, которые приходят в запросе, они не должны ничего примешивать к параметрам. Лучше это делать в явном виде в экшене контроллера

2018-04-27 08:58 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user == @question.user
Замени проверку на вызов `User#author_of?`

2018-04-27 08:58 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +  =<> link_to 'Delete answer', answer_path(answer), method: :delete, data: { confirm: 'Аre you sure?' }
Показывай ссылку только автору, зачем ее видеть всем подряд?

2018-04-27 08:58 UTC, vkurennov commented on app/views/answers/_form.html.slim
> +=form_with model: [@question, @answer], local: true do |f|
Нужен вывод ошибок валидации

2018-04-27 08:58 UTC, vkurennov commented on app/views/layouts/application.html.slim
> +    - if user_signed_in?
А ссылку на вход? Логично ее тоже расположить на всех страницах, как это обычно и делается

2018-04-27 08:58 UTC, vkurennov commented on app/views/questions/index.html.slim
> +    th Body
А где вывод самих вопросов?

2018-04-27 08:58 UTC, vkurennov commented on app/views/questions/new.html.slim
> += form_with model: @question, local: true do |f|
Нужен вывод ошибок валиадции, то что ты выводишь во флеш-сообщении, это просто оповещение, а тут нужен вывод конкретных ошибок из модели

2018-04-27 08:58 UTC, vkurennov commented on app/views/questions/show.html.slim
> += link_to 'Delete question', question_path(@question), method: :delete, data: { confirm: 'Аre you sure?' }
Показывай ссылку только автору

2018-04-27 08:58 UTC, vkurennov commented on config/routes.rb
>      resources :answers, shallow: true
Если у тебя в контроллере не все экшены нужны, то на уровне роутинга это тоже лучше указать

2018-04-27 08:58 UTC, vkurennov commented on spec/acceptance/create_answer_spec.rb
> +feature 'Create answer', %q{
Нужен сценарий на ошибки валидации - проверить, что система выводит их пользователю.

2018-04-27 08:58 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +feature 'Create question', %q{
Нужен сценарий на ошибки валидации - проверить, что система выводит их пользователю.

2018-04-27 08:58 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
Нужно проверить наличие заголовка и тела вопроса на странице

2018-04-27 08:58 UTC, vkurennov commented on spec/acceptance/delete_answer_spec.rb
> +    question
Чтобы не писать так, можно объявлять данные через `given!` (или `let!`), тогда они будут автоматом выполняться перед каждым тестом. Это как раз то же самое, что у тебя сейчас, только короче.

2018-04-27 08:58 UTC, vkurennov commented on spec/acceptance/delete_answer_spec.rb
> +    expect(page).to have_content 'Answer successfully deleted.'
Нужно проверить, что ответа больше нет на странице

2018-04-27 08:58 UTC, vkurennov commented on spec/acceptance/delete_answer_spec.rb
> +  scenario 'Not author delete answer' do
Нужен похожий сценарий для незалогиненного юзера

2018-04-27 08:58 UTC, vkurennov commented on spec/acceptance/delete_answer_spec.rb
> +    click_on 'Delete answer'
Лучше вообще не показывать ссылку на удаление не автору и проверять как раз ее отсутствие.

2018-04-27 08:58 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +    expect(page).to have_content 'Question successfully deleted.'
Нужно проверить отсутствие вопроса на странице

2018-04-27 08:58 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +  scenario 'Not author delete question' do
Нужен похожий сценарий для незалогиненного юзера

2018-04-27 08:58 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +    click_on 'Delete question'
Лучше вообще не показывать ссылку на удаление не автору и проверять как раз ее отсутствие.

2018-04-27 08:58 UTC, vkurennov commented on spec/acceptance/show_question_spec.rb
> +feature 'Show question and its answers' do
В этой же фиче надо проверить вывод **списка** ответов, причем, ответы должны быть разными, чтобы тест был верным. лучше всего это сделать через sequence в фабриках

2018-04-27 08:58 UTC, vkurennov commented on spec/acceptance/view_questions_list_spec.rb
> +    expect(page).to have_content 'Questions list'
Нет, нужно проверять контент вопросов, а не загловок. Именно из-за этого теста, который по факту, ложно-положительный, ты забыл на странице вопросов вывести список. Причем, чтобы тест был верным, нужно сделать разные вопросы.

2018-04-27 08:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    describe 'POST #create' do
При успешном создании ответа, надо также проверить связь с залогиненным юзером

2018-04-27 08:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        @request.env['devise.mapping'] = Devise.mappings[:user]
У тебя  же есть хелпер sign_in_user, который как раз и делает все это разом. А чтобы не логинить другого юзера, ты можешь создать ответ с другим юзером в качестве автора.

2018-04-27 08:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  let(:answer) { create(:answer, question: question, user: author) }
Этот объект нужен только в тестах про удаление, вот и перенеси его туда

2018-04-27 08:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    before { answer }
Объяви answer через `let!`

2018-04-27 08:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: answer } }.to_not change(question.answers, :count)
тут в change должен быть просто Answer, потому что важно, что в принципе никакой ответ не удален, вне зависимости от его связей

2018-04-27 08:58 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { user_id: author, question: attributes_for(:question) } }.to change(Question, :count).by(1)
Тут нужно проверить связь с залогиненным юзером

2018-04-27 08:58 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { user_id: author, question: attributes_for(:invalid_question) } }.to_not change(Question, :count)
Нет, user_id не передается в параметрах, мы его берем в контроллере через current_user, параметры на это никак не влияют

2018-04-27 08:58 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +  describe 'DELETE #destroy' do
См. замечания к аналогичным тестам для ответов

2018-04-27 13:16 UTC, miheykrug commented on spec/acceptance/delete_question_spec.rb
> +    expect(page).to have_content 'Question successfully deleted.'
Здесь я думал на счет этого. Но что если при большом количестве вопросов будет использоваться пагинация. Тогда есть вероятность, что на странице вопроса не будет, а из базы он не удалится.

2018-04-28 08:23 UTC, vkurennov requested changes

2018-04-28 08:23 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.user_id = current_user.id
Присваивать лучше по объектам, а вот сравнивать по id. Суть в том, что мы должны работать с объектами в большинстве случаев, а заботу о связях и полях в БД отдать ORM, именно в этом и есть смысл ORM-библиотек. А вот при сравнении мы используем id чтобы не тянуть из базы объект, который не нужен, т.е. делаем это из соображений эффективности и оптимизации, чтобы не делать лишний запрос к базе

2018-04-28 08:23 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @answers = Answer.all
Тут не верно, мы не должны показывать вообще все ответы в системе, а только ответы на данный конкретный вопрос, иначе ответы будут не релевантными

2018-04-28 08:23 UTC, vkurennov commented on app/models/user.rb
> +  def author_of?(publication)
Лучше назвать параметр как-то вроде resource, совсем не обязательно, что он будет именно неким опубликованным текстом, это сейчас так, но в будущем может измениться.

2018-04-28 08:23 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +    - if current_user && current_user.author_of?(answer)
Можно применить [safe navigation operator](http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/) и написать так: `current_user&.author_of?(answer)`

2018-04-28 08:23 UTC, vkurennov commented on app/views/questions/show.html.slim
> += render @question.answers
А зачем тогда в контроллере в show загружается переменная @answers?

2018-04-28 08:23 UTC, vkurennov commented on spec/acceptance/create_answer_spec.rb
> +    expect(page).to have_content '1 errors detected:'
Лучше сами ошибки валидации проверить

2018-04-28 08:23 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content '2 errors detected:'
Тут тоже лучше сами ошибки валидации проверить

2018-04-28 08:23 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +    click_on 'Asc question'
Кстати, "спросить" по-английски будет "Ask", k в конце, на c

2018-04-28 08:23 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +    expect(page).to have_content 'Question successfully deleted.'
Ну во-первых в этом тесте, даже при наличии пагинации, вопрос всего один в базе и пагинация не включится. Во-вторых, только остутсвие вопроса на странице доказывает (с т.з. пользователя), что ответ удален. В-третьих, если уж делать пагинацию, то после удаления, юзер должен оставаться на той же странице после удаления, но опять же это здесь никак не влияет, по первой причине.

2018-04-28 08:23 UTC, vkurennov commented on spec/acceptance/view_questions_list_spec.rb
> +    expect(page).to have_content questions[0].title
Попробуй применить цикл, код теста станет короче и гибче

2018-04-28 08:23 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
А где тесты на метод `author_of?` Любой код, который ты пишешь в моделях/контроллерах, надо тестировать

2018-04-28 15:28 UTC, vkurennov approved these changes

2018-04-28 15:28 UTC, vkurennov commented on spec/models/user_spec.rb
> +        expect(user.author_of?(question)).to be true
* rspec определяет динамические метчеры (методы для проверки) для методов-предикатов (это методы, которые заканчиваются на знак вопроса и возвращают true/false) и можно писать короче и красивее:
`expect(user).to be_author_of(question)`
т.е. название метчера получается из названия метода без вопр. знака и с добавлением `be_` в начале

2018-04-28 15:28 UTC, vkurennov commented on spec/models/user_spec.rb
> +  describe 'check if the user is the author of the resource' do
В тестах моделей, где чаще всего тестируются методы, принято на каждый метод заводить describe, а внутри писать тесты, если есть какие-то особенности, то выделять их через context, т.е. структура должна быть такая примерно в этом случае:

```
describe '#author_of?' do
  it 'returns true if the user is an author of resource'
  it 'returns false if the user is not an author of resource'
end
```

Так гораздо локаничнее и при этом емко и понятно

2018-04-29 13:55 UTC, merged